config/routes.rb
Rails.application.routes.draw do

  get 'review/new'

  get 'review/create'

  devise_for :users
  root to: 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :courses do
    member do
        post :upvote
    end
    resources :subscriptions
    resources :reviews
    resources :events do
      member do
        post :attendance
      end
    end
  end
   get 'dashboard' => 'dashboards#show'
  resources :user

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :events, dependent: :destroy
  belongs_to :user
  has_many :subscriptions
  acts_as_votable
  def votes
    self.votes_for.size
  end
end

app/models/event.rb
class Event < ApplicationRecord
  geocoded_by :location
  after_validation :geocode, if: :location_changed?
  has_many :attendances
  belongs_to :course
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :course
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :attendances
  has_many :courses
  has_many :reviews
  has_many :subscriptions
  mount_uploader :photo, PhotoUploader
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def create
    @event = Event.find(params[:event_id])
    @event = Event.find(params[:event_id])

    @attendance = Attendance.where({ user: current_user, event: @event})
    if @attendance.blank?
      @attendance  = Attendance.new({ user: current_user, event: @event})
      @attendance.status = "Attending"
      @attendance.save!
      #  redirect_to course_path(@attendance.event.course)
         #format.js  <-- will render `app/views/reviews/create.js.erb`
    else
      a = @attendance.first.destroy
    #   redirect_to course_path(a.event.course)
  end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :getCourse, only: [:show]
  def create
    if params[:course]
      @course = Course.new(course_params)

      @course.user = current_user
    end
    if @course.save
      respond_to do |format|
        format.html { redirect_to course_path(@course) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      redirect_to root_path(@course)
    end

  end

  def new
    @course=Course.new
  end

  def index
    @courses = Course.all
  end

  def show
    @event = Event.new({user: current_user, course: @course})
    check_attendance
    @subscription = Subscription.new() if @current_user_course_subscription.empty?
    @teacher = @course.user == current_user
    @reviews = Review.where(rewiew_id: @course.id)
    @review = Review.new()
    @hash = Gmaps4rails.build_markers(@course.events) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      # marker.picture({
      #             :url => ,
      #             :width   => 32,
      #             :height  => 32
      #            })
      marker.infowindow maxWidth: 80
      marker.infowindow "<h4>#{event.title}</h4>
                          <h5>#{event.title}</h5>"
      end
  end
  def upvote
    @course = Course.find(params[:id])
    if current_user.voted_for? @course
      current_user.unvote_for @course
    else
      current_user.up_votes @course
    end
  end

  private
  def getCourse
    @course = Course.find(params[:id])
  end
  def course_params
    params.require(:course).permit(:title, :content)
  end

  def check_attendance
    #false if no attendance
    course = Course.find(params[:id])
    @current_user_course_subscription = course.subscriptions.where(user: current_user)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
  end

  def new

  end
  def create
    if params[:event]
      getCourse

      @event = Event.new(event_params)
      @event.course=@course
      @event.user = current_user
      STDERR.puts @event
    end
    if @event.save!
      respond_to do |format|
        format.html { redirect_to course_path(@course) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      redirect_to root_path(@event)
    end

  end

  def index

  end

  def show
  end

  def attendance
      @event = Event.find(params[:id])

      @attendance = Attendance.where({ user: current_user, event: @event})
      if @attendance.blank?
        @attendance  = Attendance.new({ user: current_user, event: @event})
        @attendance.status = "Attending"
        @attendance.save!
        #  redirect_to course_path(@attendance.event.course)
           #format.js  <-- will render `app/views/reviews/create.js.erb`
      else
        a = @attendance.first.destroy
      #   redirect_to course_path(a.event.course)
    end
  end


  private

  def getCourse
    @course = Course.find(params[:course_id])
  end

  def getEvent
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :content, :location, :min_attendance, :max_attendance, :date, :course_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @new_course = Course.new()
    @courses = Course.all.last(5)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
  end

  def create
    if params[:review]
      @review = Review.new(review_params)
      getCourse
      @review.rewiew_id = @course.id
      @review.review_type = @course.class.name
      @review.user = current_user
      STDERR.puts @event
    end
    if @review.save!
      respond_to do |format|
        format.html { redirect_to course_path(@course) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      redirect_to root_path(@event)
    end

  end
private
  def getCourse
    @course = Course.find(params[:course_id])
  end
  def review_params
    params.require(:review).permit( :content)
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    @course = Course.find(params[:course_id])
    @subscription = Subscription.new({ user: current_user, course: @course})
    if @subscription.save!
      respond_to do |format|
        format.html { redirect_to course_path(@course) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      redirect_to root_path(@event)
    end
  end

  def new
  end

  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attendances/_form.html.erb
<%= simple_form_for(attendance) do |form| %>
<%= form.input :title, placeholder: "Title of your Course" %>
<%= form.input :content, placeholder: "Title of your Course" %>
<%= form.button :submit, class:"btn btn-primary" %>
<% end %>

app/views/courses/_course.html.erb
<h5 style="font-size: 2.5vw;"> <%= course.title %> </h5>
<h6 style="font-size: 2.5vw;"> <%= course.content %> </h6>

app/views/courses/_form.html.erb
<%= simple_form_for(course) do |form| %>
<%= form.input :title, placeholder: "Title of your Course" %>
<%= form.input :content, placeholder: "Title of your Course" %>
<%= form.button :submit, class:"btn btn-primary" %>
<% end %>

app/views/courses/index.html.erb
<h1>Courses Index</h1>

<div class="slideDown">
<%= react_component "CourseList",
      render(template: 'courses/index.json.jbuilder') %>

      <h1> Booom</h1>
<% @courses.each do |course| %>
<% link_to course_path(course) do %>
    <% render 'courses/course', course:course %>
    <% end %>
<% end %>
</div>
n 

app/views/courses/new.html.erb
<div class="text-center">
   <h1> Create a course </h1>
  <%= render 'courses/form', course:@course %>

</div>

app/views/courses/show.html.erb
<div class="row">
  <div class="col-sm-8">

    <h1> <%= @course.title %> </h1>
    <h2> <%= simple_format(@course.content) %></h2>
    <br>
    <h2> Given by: <%= @course.user.email %></h2>
    <% if @current_user_course_subscription.empty? %>
    <%= simple_form_for @subscription , url: course_subscriptions_path(@course) do |form| %>
    <%= form.button :submit,label:"Subscribe to This Course", class:"btn btn-lg btn-primary" %>
    <% end %>
    <% else %>
    <h3 style="red"> subscribed !</h3>
    <% end %>
    <b> They've subscribed already: </b>
    <% @course.subscriptions.each do |sub| %>
    <p>
      <%= sub.user.email %>
    </p>
    <% end %>
  </div>
</div>


<div class="row">
  <div class="col-sm-4">

    <% if @teacher then %>
    <%= render 'events/form', event:@event%>
    <% end %>
    <b>reviews: </b>
    <% @reviews.each do |rew| %>
    <h5> <i><%= rew.content %> </i> by: <b> <%= rew.user.email %> </b>  </h5>
    <% end %>
  </div>


  <div class="col-sm-6">


    <% unless @current_user_course_subscription.empty?%>
    <%= render 'review/form', review: @review %>
    <% end %>

  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <b>classes: </b>
    <%= react_component "EventList",
          render(template: 'events/index.json.jbuilder') %>
    <% @course.events.each do |event| %>
    <div class="col-sm-4">
      <% render 'events/event', event:event, teacher: @teacher%>
    </div>
    <% end %>

    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>


  </div>
</div>
<div id="map" style='width: 100%; height: 200px;' class= 'img-res'>

</div>


<% content_for(:after_js) do %>
<script type="text/javascript">
$(document).on('ready', function() {
  var handler = Gmaps.build('Google');
  handler.buildMap({ provider: {scrollwheel: false}, internal: { id: 'map' } }, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    if (markers.length == 0) {
      handler.getMap().setZoom(2);
    } else if (markers.length == 1) {
      handler.getMap().setZoom(12);
    }
  });
});

</script>
<%end%>

app/views/events/_event.html.erb
<div class="row" style="border-style: groove">

  <div class="col-sm-6">

    <h4>  what: <b>  <%= event.title %> </b></h4>
    <h4> what what ? <b> <%= event.content %> </b> </h4>
    <h4> when: <b> <%= event.date %> </b></h4>
    <h4> where: <b> <%= event.location %> </b> </h4>

  </div>

  <div class="col-sm-6">
    <h4> How many: <%= event.attendances.count %> </h4>
    <h4>min attendance  for course: <%= event.min_attendance %> </h4>
    <h4>max attendance  for course: <%= event.max_attendance %> </h4>
    <% unless teacher %>
      <% if event.attendances.where(user: current_user).empty? && event.attendances.length < event.max_attendance %>
        <%= simple_form_for Attendance.new(event: event), url: course_event_attendances_path(event.course, event) do |form| %>
          <%= form.submit 'submit' %>
        <% end %>
      <% elsif event.attendances.length == event.max_attendance %>
            <h5> Max out class </h5>
      <%else %>
    <h7 class="btn btn-warning"> <%= event.attendances.where(user: current_user).first.status %> </h7>
    <% end %>
  <% end %>
   <h5> <b>attendees: </b></h5>
   <ul>

  <% event.attendances.each do |attendance| %>
  <li> <h6> <%= attendance.user.email %></h6> </li>
  <% end %>
  </ul>
</div>
</div>

app/views/events/_form.html.erb
<h4>
  <b>Create an Event </b>
</h4>

<%= simple_form_for  event, url: course_events_path(@course), method: 'post'  do |form| %>
<%= form.input :date, placeholder: "Date" %>
<%= form.input :title, placeholder: "Title for this class" %>
<%= form.input :content, placeholder: "Content of this class" %>
<%= form.input :location, as: :string,  placeholder: "Location" %>
<%= form.input :min_attendance, placeholder: "Minimum attendance" %>
<%= form.input :max_attendance, placeholder: "Maximum attendance" %>
<%= form.button :submit, class:"btn btn-primary" %>
<% end %>

<%= content_for(:after_js) do %>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teach Anywhere ! </title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyAw09Zw9tLYxAxAGWfsJJ9lIML795J3QUs"></script>

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
      </div>
      <%= javascript_include_tag 'application' %>
      <% # javascript_include_tag "https://maps.google.com/maps/api/js" %>

          <%= yield(:after_js) %>

  <!-- Include Google Maps JS library. You should use your *own* key

  <script src="https://maps.google.com/maps/api/js?key=AIzaSyCaDssjTkalIWXw_mk68sGREktIzCU9Qpg"></script> -->

  <!-- Include Dependencies of GMaps for Rails gem -->
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js" >
</script>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= render 'courses/form', course:@new_course %>
<div class="row">

  <% @courses.each do |course| %>
  <%= link_to course_path(course) do %>

  <div class="col-sm-3">
    <%= render partial: 'courses/course', locals: { course:course } %>
  </div>

  <% end %>
  <% end %>
</div>

app/views/review/_form.html.erb
<%= simple_form_for(review,  url: course_reviews_path(@course), method: 'post' ) do |form| %>
  <%= form.input :content, placeholder: "Your Review" %>
  <%= form.button :submit, class:"btn btn-primary" %>

<% end %>

app/views/review/create.html.erb
<h1>Review#create</h1>
<p>Find me in app/views/review/create.html.erb</p>

app/views/review/new.html.erb
<h1>Review#new</h1>
<p>Find me in app/views/review/new.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    hey hey
  <% end %>
  <%= link_to 'Courses' ,courses_path %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
<!--     <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
    <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "create a project", new_course_path %>
    </div>
      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.photo || "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "profile", user_path(current_user) %></li>
          <li><%= link_to "dashboard", dashboard_path %></li>
          <li></li>
          <li id="logout"><%= link_to "log out", destroy_user_session_path, method: "delete" %></li>
        </ul>
        </div>
      </div>

    <% else %>

      <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
<!--     <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %> -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/subscriptions/create.html.erb
<h1>Subscriptions#create</h1>
<p>Find me in app/views/subscriptions/create.html.erb</p>

app/views/subscriptions/index.html.erb
<h1>Subscriptions#index</h1>
<p>Find me in app/views/subscriptions/index.html.erb</p>

app/views/subscriptions/new.html.erb
<h1>Subscriptions#new</h1>
<p>Find me in app/views/subscriptions/new.html.erb</p>

app/views/subscriptions/show.html.erb
<h1>Subscriptions#show</h1>
<p>Find me in app/views/subscriptions/show.html.erb</p>